/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as AuthenticatedAppWhatsappRouteImport } from './routes/_authenticated/app.whatsapp'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/app.tasks'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppRenaveRouteImport } from './routes/_authenticated/app.renave'
import { Route as AuthenticatedAppPipelineRouteImport } from './routes/_authenticated/app.pipeline'
import { Route as AuthenticatedAppLabelsRouteImport } from './routes/_authenticated/app.labels'
import { Route as AuthenticatedAppConversationsRouteImport } from './routes/_authenticated/app.conversations'
import { Route as AuthenticatedAppContactsRouteImport } from './routes/_authenticated/app.contacts'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/app.ai'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as ApiPublicWebhooksFocusNfeRouteImport } from './routes/api/public/webhooks/focus-nfe'
import { Route as ApiPublicWebhooksEvolutionRouteImport } from './routes/api/public/webhooks/evolution'
import { Route as ApiPublicHooksRunRecurringAutomationsRouteImport } from './routes/api/public/hooks/run-recurring-automations'
import { Route as ApiPublicHooksDrainWebhookQueueRouteImport } from './routes/api/public/hooks/drain-webhook-queue'
import { Route as ApiPublicHooksDrainRenaveQueueRouteImport } from './routes/api/public/hooks/drain-renave-queue'
import { Route as ApiPublicWebhooksWhatsappNumberIdRouteImport } from './routes/api/public/webhooks/whatsapp.$numberId'
import { Route as ApiPublicWebhooksEvolutionNumberIdRouteImport } from './routes/api/public/webhooks/evolution.$numberId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWhatsappRoute =
  AuthenticatedAppWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRenaveRoute = AuthenticatedAppRenaveRouteImport.update({
  id: '/renave',
  path: '/renave',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPipelineRoute =
  AuthenticatedAppPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLabelsRoute = AuthenticatedAppLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConversationsRoute =
  AuthenticatedAppConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContactsRoute =
  AuthenticatedAppContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicWebhooksFocusNfeRoute =
  ApiPublicWebhooksFocusNfeRouteImport.update({
    id: '/api/public/webhooks/focus-nfe',
    path: '/api/public/webhooks/focus-nfe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksEvolutionRoute =
  ApiPublicWebhooksEvolutionRouteImport.update({
    id: '/api/public/webhooks/evolution',
    path: '/api/public/webhooks/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunRecurringAutomationsRoute =
  ApiPublicHooksRunRecurringAutomationsRouteImport.update({
    id: '/api/public/hooks/run-recurring-automations',
    path: '/api/public/hooks/run-recurring-automations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDrainWebhookQueueRoute =
  ApiPublicHooksDrainWebhookQueueRouteImport.update({
    id: '/api/public/hooks/drain-webhook-queue',
    path: '/api/public/hooks/drain-webhook-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDrainRenaveQueueRoute =
  ApiPublicHooksDrainRenaveQueueRouteImport.update({
    id: '/api/public/hooks/drain-renave-queue',
    path: '/api/public/hooks/drain-renave-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksWhatsappNumberIdRoute =
  ApiPublicWebhooksWhatsappNumberIdRouteImport.update({
    id: '/api/public/webhooks/whatsapp/$numberId',
    path: '/api/public/webhooks/whatsapp/$numberId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksEvolutionNumberIdRoute =
  ApiPublicWebhooksEvolutionNumberIdRouteImport.update({
    id: '/$numberId',
    path: '/$numberId',
    getParentRoute: () => ApiPublicWebhooksEvolutionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/conversations': typeof AuthenticatedAppConversationsRoute
  '/app/labels': typeof AuthenticatedAppLabelsRoute
  '/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/app/renave': typeof AuthenticatedAppRenaveRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/drain-renave-queue': typeof ApiPublicHooksDrainRenaveQueueRoute
  '/api/public/hooks/drain-webhook-queue': typeof ApiPublicHooksDrainWebhookQueueRoute
  '/api/public/hooks/run-recurring-automations': typeof ApiPublicHooksRunRecurringAutomationsRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRouteWithChildren
  '/api/public/webhooks/focus-nfe': typeof ApiPublicWebhooksFocusNfeRoute
  '/api/public/webhooks/evolution/$numberId': typeof ApiPublicWebhooksEvolutionNumberIdRoute
  '/api/public/webhooks/whatsapp/$numberId': typeof ApiPublicWebhooksWhatsappNumberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/conversations': typeof AuthenticatedAppConversationsRoute
  '/app/labels': typeof AuthenticatedAppLabelsRoute
  '/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/app/renave': typeof AuthenticatedAppRenaveRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/drain-renave-queue': typeof ApiPublicHooksDrainRenaveQueueRoute
  '/api/public/hooks/drain-webhook-queue': typeof ApiPublicHooksDrainWebhookQueueRoute
  '/api/public/hooks/run-recurring-automations': typeof ApiPublicHooksRunRecurringAutomationsRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRouteWithChildren
  '/api/public/webhooks/focus-nfe': typeof ApiPublicWebhooksFocusNfeRoute
  '/api/public/webhooks/evolution/$numberId': typeof ApiPublicWebhooksEvolutionNumberIdRoute
  '/api/public/webhooks/whatsapp/$numberId': typeof ApiPublicWebhooksWhatsappNumberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRoute
  '/_authenticated/app/contacts': typeof AuthenticatedAppContactsRoute
  '/_authenticated/app/conversations': typeof AuthenticatedAppConversationsRoute
  '/_authenticated/app/labels': typeof AuthenticatedAppLabelsRoute
  '/_authenticated/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/_authenticated/app/renave': typeof AuthenticatedAppRenaveRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/drain-renave-queue': typeof ApiPublicHooksDrainRenaveQueueRoute
  '/api/public/hooks/drain-webhook-queue': typeof ApiPublicHooksDrainWebhookQueueRoute
  '/api/public/hooks/run-recurring-automations': typeof ApiPublicHooksRunRecurringAutomationsRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRouteWithChildren
  '/api/public/webhooks/focus-nfe': typeof ApiPublicWebhooksFocusNfeRoute
  '/api/public/webhooks/evolution/$numberId': typeof ApiPublicWebhooksEvolutionNumberIdRoute
  '/api/public/webhooks/whatsapp/$numberId': typeof ApiPublicWebhooksWhatsappNumberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/onboarding'
    | '/app/admin'
    | '/app/ai'
    | '/app/contacts'
    | '/app/conversations'
    | '/app/labels'
    | '/app/pipeline'
    | '/app/renave'
    | '/app/settings'
    | '/app/tasks'
    | '/app/whatsapp'
    | '/api/ai/chat'
    | '/api/public/health'
    | '/app/'
    | '/api/public/hooks/drain-renave-queue'
    | '/api/public/hooks/drain-webhook-queue'
    | '/api/public/hooks/run-recurring-automations'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/focus-nfe'
    | '/api/public/webhooks/evolution/$numberId'
    | '/api/public/webhooks/whatsapp/$numberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/admin'
    | '/app/ai'
    | '/app/contacts'
    | '/app/conversations'
    | '/app/labels'
    | '/app/pipeline'
    | '/app/renave'
    | '/app/settings'
    | '/app/tasks'
    | '/app/whatsapp'
    | '/api/ai/chat'
    | '/api/public/health'
    | '/app'
    | '/api/public/hooks/drain-renave-queue'
    | '/api/public/hooks/drain-webhook-queue'
    | '/api/public/hooks/run-recurring-automations'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/focus-nfe'
    | '/api/public/webhooks/evolution/$numberId'
    | '/api/public/webhooks/whatsapp/$numberId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/contacts'
    | '/_authenticated/app/conversations'
    | '/_authenticated/app/labels'
    | '/_authenticated/app/pipeline'
    | '/_authenticated/app/renave'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/tasks'
    | '/_authenticated/app/whatsapp'
    | '/api/ai/chat'
    | '/api/public/health'
    | '/_authenticated/app/'
    | '/api/public/hooks/drain-renave-queue'
    | '/api/public/hooks/drain-webhook-queue'
    | '/api/public/hooks/run-recurring-automations'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/focus-nfe'
    | '/api/public/webhooks/evolution/$numberId'
    | '/api/public/webhooks/whatsapp/$numberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicHooksDrainRenaveQueueRoute: typeof ApiPublicHooksDrainRenaveQueueRoute
  ApiPublicHooksDrainWebhookQueueRoute: typeof ApiPublicHooksDrainWebhookQueueRoute
  ApiPublicHooksRunRecurringAutomationsRoute: typeof ApiPublicHooksRunRecurringAutomationsRoute
  ApiPublicWebhooksEvolutionRoute: typeof ApiPublicWebhooksEvolutionRouteWithChildren
  ApiPublicWebhooksFocusNfeRoute: typeof ApiPublicWebhooksFocusNfeRoute
  ApiPublicWebhooksWhatsappNumberIdRoute: typeof ApiPublicWebhooksWhatsappNumberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/whatsapp': {
      id: '/_authenticated/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AuthenticatedAppWhatsappRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tasks': {
      id: '/_authenticated/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/renave': {
      id: '/_authenticated/app/renave'
      path: '/renave'
      fullPath: '/app/renave'
      preLoaderRoute: typeof AuthenticatedAppRenaveRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pipeline': {
      id: '/_authenticated/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AuthenticatedAppPipelineRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/labels': {
      id: '/_authenticated/app/labels'
      path: '/labels'
      fullPath: '/app/labels'
      preLoaderRoute: typeof AuthenticatedAppLabelsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conversations': {
      id: '/_authenticated/app/conversations'
      path: '/conversations'
      fullPath: '/app/conversations'
      preLoaderRoute: typeof AuthenticatedAppConversationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contacts': {
      id: '/_authenticated/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AuthenticatedAppContactsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/webhooks/focus-nfe': {
      id: '/api/public/webhooks/focus-nfe'
      path: '/api/public/webhooks/focus-nfe'
      fullPath: '/api/public/webhooks/focus-nfe'
      preLoaderRoute: typeof ApiPublicWebhooksFocusNfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/evolution': {
      id: '/api/public/webhooks/evolution'
      path: '/api/public/webhooks/evolution'
      fullPath: '/api/public/webhooks/evolution'
      preLoaderRoute: typeof ApiPublicWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-recurring-automations': {
      id: '/api/public/hooks/run-recurring-automations'
      path: '/api/public/hooks/run-recurring-automations'
      fullPath: '/api/public/hooks/run-recurring-automations'
      preLoaderRoute: typeof ApiPublicHooksRunRecurringAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drain-webhook-queue': {
      id: '/api/public/hooks/drain-webhook-queue'
      path: '/api/public/hooks/drain-webhook-queue'
      fullPath: '/api/public/hooks/drain-webhook-queue'
      preLoaderRoute: typeof ApiPublicHooksDrainWebhookQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drain-renave-queue': {
      id: '/api/public/hooks/drain-renave-queue'
      path: '/api/public/hooks/drain-renave-queue'
      fullPath: '/api/public/hooks/drain-renave-queue'
      preLoaderRoute: typeof ApiPublicHooksDrainRenaveQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/whatsapp/$numberId': {
      id: '/api/public/webhooks/whatsapp/$numberId'
      path: '/api/public/webhooks/whatsapp/$numberId'
      fullPath: '/api/public/webhooks/whatsapp/$numberId'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappNumberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/evolution/$numberId': {
      id: '/api/public/webhooks/evolution/$numberId'
      path: '/$numberId'
      fullPath: '/api/public/webhooks/evolution/$numberId'
      preLoaderRoute: typeof ApiPublicWebhooksEvolutionNumberIdRouteImport
      parentRoute: typeof ApiPublicWebhooksEvolutionRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRoute
  AuthenticatedAppContactsRoute: typeof AuthenticatedAppContactsRoute
  AuthenticatedAppConversationsRoute: typeof AuthenticatedAppConversationsRoute
  AuthenticatedAppLabelsRoute: typeof AuthenticatedAppLabelsRoute
  AuthenticatedAppPipelineRoute: typeof AuthenticatedAppPipelineRoute
  AuthenticatedAppRenaveRoute: typeof AuthenticatedAppRenaveRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
  AuthenticatedAppWhatsappRoute: typeof AuthenticatedAppWhatsappRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppAiRoute: AuthenticatedAppAiRoute,
  AuthenticatedAppContactsRoute: AuthenticatedAppContactsRoute,
  AuthenticatedAppConversationsRoute: AuthenticatedAppConversationsRoute,
  AuthenticatedAppLabelsRoute: AuthenticatedAppLabelsRoute,
  AuthenticatedAppPipelineRoute: AuthenticatedAppPipelineRoute,
  AuthenticatedAppRenaveRoute: AuthenticatedAppRenaveRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
  AuthenticatedAppWhatsappRoute: AuthenticatedAppWhatsappRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicWebhooksEvolutionRouteChildren {
  ApiPublicWebhooksEvolutionNumberIdRoute: typeof ApiPublicWebhooksEvolutionNumberIdRoute
}

const ApiPublicWebhooksEvolutionRouteChildren: ApiPublicWebhooksEvolutionRouteChildren =
  {
    ApiPublicWebhooksEvolutionNumberIdRoute:
      ApiPublicWebhooksEvolutionNumberIdRoute,
  }

const ApiPublicWebhooksEvolutionRouteWithChildren =
  ApiPublicWebhooksEvolutionRoute._addFileChildren(
    ApiPublicWebhooksEvolutionRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicHooksDrainRenaveQueueRoute: ApiPublicHooksDrainRenaveQueueRoute,
  ApiPublicHooksDrainWebhookQueueRoute: ApiPublicHooksDrainWebhookQueueRoute,
  ApiPublicHooksRunRecurringAutomationsRoute:
    ApiPublicHooksRunRecurringAutomationsRoute,
  ApiPublicWebhooksEvolutionRoute: ApiPublicWebhooksEvolutionRouteWithChildren,
  ApiPublicWebhooksFocusNfeRoute: ApiPublicWebhooksFocusNfeRoute,
  ApiPublicWebhooksWhatsappNumberIdRoute:
    ApiPublicWebhooksWhatsappNumberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
