// This file is automatically generated. Do not edit it directly.
// Server function middleware that validates the request bearer token and
// exposes a Supabase client acting as the signed-in user (RLS applies).
import { createMiddleware } from '@tanstack/react-start'
import { getRequestHeader } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_')
}

function createSupabaseFetch(supabaseKey: string, accessToken: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    )

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value))
    }

    headers.set('apikey', supabaseKey)
    if (!isNewSupabaseApiKey(accessToken)) {
      headers.set('Authorization', `Bearer ${accessToken}`)
    }

    return fetch(input, { ...init, headers })
  }
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.VITE_SUPABASE_PUBLISHABLE_KEY

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      throw new Response('Supabase not configured', { status: 500 })
    }

    const authHeader = getRequestHeader('authorization') ?? getRequestHeader('Authorization')
    const accessToken = authHeader?.replace(/^Bearer\s+/i, '').trim()

    if (!accessToken) {
      throw new Response('Unauthorized', { status: 401 })
    }

    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        headers: { Authorization: `Bearer ${accessToken}` },
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY, accessToken),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    })

    const { data, error } = await supabase.auth.getUser(accessToken)
    if (error || !data.user) {
      throw new Response('Unauthorized', { status: 401 })
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        user: data.user,
        claims: data.user,
        accessToken,
      },
    })
  },
)
